module.exports = {
  apps: [
    {
      name: "markdawn-api",
      cwd: "/var/www/markdawn/packages/api",
      script: "dist/index.mjs",
      instances: 1,
      exec_mode: "fork",
      env: {
        NODE_ENV: "production",
        PORT: 3001,
      },
      error_file: "/var/log/markdawn/api.err.log",
      out_file: "/var/log/markdawn/api.out.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
      merge_logs: true,
      autorestart: true,
      max_restarts: 5,
      min_uptime: "10s",
    },
    {
      name: "markdawn-collab",
      cwd: "/var/www/markdawn/packages/collab",
      script: "dist/index.js",
      instances: 1,
      exec_mode: "fork",
      env: {
        NODE_ENV: "production",
        COLLAB_PORT: 1234,
      },
      error_file: "/var/log/markdawn/collab.err.log",
      out_file: "/var/log/markdawn/collab.out.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
      merge_logs: true,
      autorestart: true,
      max_restarts: 5,
      min_uptime: "10s",
    },
  ],
};
